name: Deploy SimpleWebApi to ECS

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Publish
        run: dotnet publish SimpleWebApi/SimpleWebApi.csproj -c Release -o ./publish

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simple-web-api
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG SimpleWebApi/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          aws cloudformation deploy \
            --stack-name SimpleWebApiStack \
            --template-file SimpleWebApi-ECS.yml \
            --parameter-overrides \
              EnvironmentValue=Development \
              DockerImage=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
              VpcId=vpc-0137808b115ef5e78 \
              PublicSubnet1=subnet-48a \
              PublicSubnet2=subnet-49b \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ap-southeast-1